### ISSUE TITLE
Setting WHITELIST_KEYWORDS to any value throws an error

### ISSUE THREAD

**Issue by earlruby** [Symantec/slack-autoarchive#22]
Setting WHITELIST_KEYWORDS to any value throws an error:

```
$ export SLACK_TOKEN=[token]
$ export WHITELIST_KEYWORDS=xyzzy
$ PYTHONIOENCODING=UTF-8 python slack-autoarchive.py
THIS IS A DRY RUN. NO CHANNELS ARE ACTUALLY ARCHIVED.
.Traceback (most recent call last):
  File "slack-autoarchive.py", line 205, in <module>
    if (not is_channel_whitelisted(channel, whitelist_keywords) and
  File "slack-autoarchive.py", line 148, in is_channel_whitelisted
    if kw in channel['name']:
TypeError: coercing to Unicode: need string or buffer, list found

$ unset WHITELIST_KEYWORDS
$ PYTHONIOENCODING=UTF-8 python slack-autoarchive.py
THIS IS A DRY RUN. NO CHANNELS ARE ACTUALLY ARCHIVED.
.Archiving channel... alternative_facts
.Archiving channel... animals
...
```

Also tried comma-delimited lists of keywords and setting or unsetting `PYTHONIOENCODING`. Same error occurs.

**Comment by JohnTheodore** [comment]
Fixed in https://github.com/Symantec/slack-autoarchive/commit/acfa910a08184d9ff3fe37e661b131a18cb1be33
