### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by ammario** [Symantec/slack-autoarchive#43]
```
root@bot:~/slack-autoarchive# docker run -e SLACK_TOKEN=xxxxx autoarchive
2020-04-09 23:40:35,604 - INFO - THIS IS A DRY RUN. NO CHANNELS ARE ACTUALLY ARCHIVED.
.Traceback (most recent call last):
  File "slack_autoarchive.py", line 253, in <module>
    CHANNEL_REAPER.main()
  File "slack_autoarchive.py", line 241, in main
    channel_disused = self.is_channel_disused(
  File "slack_autoarchive.py", line 152, in is_channel_disused
    (last_message_datetime, is_user) = self.get_last_message_timestamp(
  File "slack_autoarchive.py", line 124, in get_last_message_timestamp
    if 'messages' not in channel_history:
TypeError: argument of type 'NoneType' is not iterable
```

Same happens when calling script directly.

**Comment by Dextro** [comment]
<img width="995" alt="Slack API: Applications " src="https://user-images.githubusercontent.com/14020/79879674-4cf88800-83ef-11ea-9d1c-e753f069adc1.png">

You need to use _OAuth Access Token_ and not _Bot User OAuth Access Token_.

**Comment by ammario** [comment]
![Screen Shot 2020-04-23 at 1 48 44 PM](https://user-images.githubusercontent.com/7416144/80137723-54dc3780-8569-11ea-8758-9d504471d8a4.png)

All I see is the one.

**Comment by jonathanchan** [comment]
@ammario if you're still running getting a NoneType error, try my update - https://github.com/jonathanchan/slack-autoarchive.
